config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :articles do
  	post 'like', on: :member
  end
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get "/pages/:page" => "pages#show"

  get "/blog" => "articles#blog"
  get "/tutorials" => "articles#tutorials"

  get "/blog" => "articles#filter_articles"

  put "/blog" => "articles#like"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	scope :article_type, -> (article_type) { where(article_type: article_type) }
	
	#scope :article_type_without_tutorials, -> { article_type.where.not(article_type: 'Tutorial') }
	#def self.filter(code, life)
	#	if code && life
	#		where("article_type = 'Code' AND article_type = 'Lifestyle'").order('postdate DESC')
	#	elsif !code && life
	#		where("article_type = 'Lifestyle'").order('postdate DESC')
	#	elsif code && !life
	#		where("article_type = 'Code'").order('postdate DESC')
	#	elsif !code && !life
	#		where("article_type = ''")
	#	end
	#end
end		

app/models/home.rb
class Home < ApplicationRecord

	

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Srespond_to :js
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #respond_to :html, :js
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # Show both code and lifestyle blog articles
  # GET /blog 
  def blog
    @blog_articles = Article.where(nil).where.not(article_type: 'Tutorial').order('postdate DESC')
    @blog_articles = @blog_articles.article_type(params[:filter]) if params[:filter].present?
  
    respond_to do |format|
      format.html { render :blog }
      format.js   { render layout: false }
    end
  end

  def tutorials
    @tutorials = Article.where("article_type = 'Tutorial'").order('postdate DESC')
  end

  #increment the upvotes for a single article
  def like
    @article = Article.find(params[:id])
    @article.increment! :upvotes
    @likes = @article.upvotes

    respond_to do |format|
      format.html { redirect_to :blog }
      format.js   { render layout: false }
    end
  end

  def unlike

  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:article_name, :article_body, :article_type, :upvotes, :postdate, :main_img_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@tutorial = Article.where(article_type: 'Tutorial').order(:upvotes).last
  	@code_article = Article.where(article_type: 'Code').order(:postdate).last
  	@life_article = Article.where(article_type: 'Lifestyle').order(:postdate).last
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
      if valid_page?
        render template: "pages/#{params[:page]}"
      else
        render file: "public/404.html", status: :not_found
      end
    end

    private
    def valid_page?
      File.file?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password_digest, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_blog.html.erb
<div id="articles">
	<% articles.each do |post| %>
	<hr />	
		<div id="article_<%= post.id %>" class="article">

			<h2><%= post.article_name %> </h2>

			<p class="article-date">
				<%= post.postdate.strftime("%A, %B %d, %Y") %>
			</p>

			<%= image_tag post.main_img_url, :class => "main" %>

			<p>
				<%= truncate(post.article_body, length: 500) { link_to "Read more", article_path(post.id) } %>
			</p>
			<div class="likes"> 
				<%= render('like', post: post) %>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_name %>
    <%= form.text_field :article_name, id: :article_article_name %>
  </div>

  <div class="field">
    <%= form.label :article_body %>
    <%= form.text_area :article_body, id: :article_article_body %>
  </div>

  <div class="field">
    <%= form.label :article_type %>
    <%= form.text_field :article_type, id: :article_article_type %>
  </div>

  <div class="field">
    <%= form.label :upvotes %>
    <%= form.text_field :upvotes, id: :article_upvotes %>
  </div>

  <div class="field">
    <%= form.label :postdate %>
    <%= form.date_select :postdate, id: :article_postdate %>
  </div>

  <div class="field">
    <%= form.label :main_img_url %>
    <%= form.text_field :main_img_url, id: :article_main_img_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_like.html.erb
<%= button_to like_article_path(post), class: 'btn btn-like', :remote => true  do %>
	<%= fa_icon "heart" %>
<% end %>
<div class="like-num">
  <div class="likes">
		<%= post.upvotes %>
	</div>
</div>

app/views/articles/blog.html.erb
<div class="filter-buttons">

	<h5>Blog Filter:</h5>

	<%= button_to "All", blog_path, class: 'btn-filter all selected', method: :get, params: { filter: "" }, remote: true %>

	<%= button_to "Code", blog_path, class: 'btn-filter code', method: :get, params: { filter: "Code" }, remote: true %>

	<%= button_to "Lifestyle", blog_path, class: 'btn-filter life', method: :get, params: { filter: "Lifestyle" }, remote: true %>

</div>
	<!-- <button type="button" id="<%= @code_filter %>_filter" class="btn btn-secondary btn-code">
		Code
	</button>
	<button type="button" id="<%= @code_filter %>_filter" class="btn btn-secondary btn-life">
		Lifesyle
	</button> -->
<!-- </div> -->
<div class="articles">
	<%= render('blog', articles: @blog_articles) %>
</div>

app/views/articles/blog.js.erb
$(".articles").html("<%= escape_javascript(render('blog', articles: @blog_articles )) %>");

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/filter.js.erb
var articles = getElementById("articles");
articles.html("<%= escape_javascript(render partial: 'filter', locals: { articles: @article_list }) %>");

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Article name</th>
      <th>Article body</th>
      <th>Article type</th>
      <th>Upvotes</th>
      <th>Postdate</th>
      <th>Main img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.article_name %></td>
        <td><%= article.article_body %></td>
        <td><%= article.article_type %></td>
        <td><%= article.upvotes %></td>
        <td><%= article.postdate %></td>
        <td><%= article.main_img_url %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/like.js.erb
$("#article_<%= @article.id %> .likes").html("<%= escape_javascript(render partial: 'like', locals: { post: @article }) %>");
$("#article_<%= @article.id %> .btn-like").toggleClass("clicked");

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article name:</strong>
  <%= @article.article_name %>
</p>

<p>
  <strong>Article body:</strong>
  <%= @article.article_body %>
</p>

<p>
  <strong>Article type:</strong>
  <%= @article.article_type %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @article.upvotes %>
</p>

<p>
  <strong>Postdate:</strong>
  <%= @article.postdate %>
</p>

<p>
  <strong>Main img url:</strong>
  <%= @article.main_img_url %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/tutorials.html.erb
<p id="notice"><%= notice %></p>

<div class="filter">
	<h5>Blog Filter:</h5>
	<button type="button" class="btn btn-secondary btn-code">
		Ruby on Rails
	</button>
	<button type="button" class="btn btn-secondary btn-life">
		Java
	</button>
</div>

<%= render('blog', articles: @tutorials) %>

app/views/home/index.html.erb
<div class="card">
	<div class="card-header">
    	Recent Article
    </div>
    <div class="card-body">
    	<h2 class="card-title">
    		<%= @tutorial.article_name %>
    	</h2>
    	<p>
	    <medium class="text-muted">
	    	<%= @tutorial.postdate.strftime("%A, %B %d, %Y") %>
	    </medium>
  	</p>
    	<p class="card-text">
    	<%= truncate(@tutorial.article_body, length: 350) { link_to "Read more", article_path(@tutorial.id) } %>
    </p>
    </div>
</div>
</div>

<div class="row">
	<div class="col-sm-12 col-md-6">
		<div class="card">
		<!-- <img class="card-img-top" src="https://image.ibb.co/iGgh7n/code_faux_img.jpg" alt="Card image cap"> -->
		<%= image_tag @code_article.main_img_url, :class => "card-img-top" %>
		<div class="card-body">
	    <h5 class="card-title right">CODE</h5>
	    <h6 class="card-subtitle mb-2 text-muted">
	    	<%= @code_article.article_name %>
	    </h6>
	    <p>
		    <small class="text-muted">
	    		<%= @code_article.postdate.strftime("%A, %B %d, %Y") %>
	    	</small>
    	</p>
	    <p class="card-text">
	    	<%= truncate(@code_article.article_body, length: 350) { link_to "Read more", article_path(@code_article.id) } %>
	    </p>
	    <!-- <a href="#" class="card-link">Read more...</a> -->
	  </div>
	</div>
	</div>
	<div class="col-sm-12 col-md-6">
		<div class="card">
		<!-- <img class="card-img-top" src="https://image.ibb.co/kR5mYS/life_faux_img.jpg" alt="Card image cap"> -->
		<%= image_tag @life_article.main_img_url, :class => "card-img-top" %>
		<div class="card-body">
	    <h5 class="card-title right">LIFESTYLE</h5>
	    <h6 class="card-subtitle mb-2 text-muted">
	    	<%= @life_article.article_name %>
	    </h6>
	    <p>
		    <small class="text-muted">
	  			<%= @life_article.postdate.strftime("%A, %B %d, %Y") %>
	  		</small>
  		</p>
	    <p class="card-text">
	    	<%= truncate(@life_article.article_body, length: 350) { link_to "Read more", article_path(@life_article.id) } %>
	    </p>
	    <!-- <a href="#" class="card-link">Read more...</a> -->
	  </div>
	</div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="logo-wrapper">
    <%= image_tag "lotus-flower", class: "logo" %>
  </div>

  <div class="name-wrapper">
    <span class="codelily">codelily</span>
    <!-- <span class="lily">lily</span> -->
  </div>
</header>

app/views/layouts/_navbar.html.erb
<div class="navbar-non-bs">
  <ul>
    <li><%= link_to "home", "/" %></li>
    <li>|</li>
    <li><%= link_to "about", root_url + "pages/about" %></li>
    <li>|</li>
    <li><a href=#>tech</a></li>
    <li>|</li>
    <li><a href=#>lifestyle</a></li>
    <li>|</li>
    <li><a href=#>relationship</a></li>
    <li>|</li>
    <li><a href=#>career</a></li>
    <li>|</li>
    <li><a href=#>hobby</a></li>
  </ul> 
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
<img class="biopic" src="<%= asset_path('biopic.jpg') %>">
      <p><span class="bioname">Mandi Gunningham</span></p>
      <p><span class="bio">
      	A rennaissance woman trying to live a balanced life. <br><br>
      	Coder. Wife. Creative. Cat Mom.<br><br>
      	Lover of fasion, tech, travel, and games.<br><br>
      	<%= link_to "More about me...", root_url + "pages/about" %>
      </span></p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codelily</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
	<!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- <script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script> -->
		<!-- <script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script> -->
		<!-- <script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script> -->
	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

  </head>

 	<!-- BOOTSTRAP JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div id="container">
    	
		<div id="wrapper">
			<%= render "layouts/header" %>

	      	<%= render "layouts/navbar" %>

	      	<%= render "layouts/sidebar" %>
		

			<body>
				<%= yield %>
			</body>

		</div>

	</div>

</html>

app/views/pages/bio.html.erb
<h2>Hi, my name is Mandi Matchett</h2>
<%= image_tag "me_old.jpg", :class => "rounded-circle col-xs-12 col-sm-4 d-block mx-auto" %>

	<h4>I am currently working on my MS in Applied Computer Science and will graduate in July 2018!</h4>
	<h5>My Past</h5>
	<p>
		As a teen and young adult my identity centered almost solely around my artistic side.  I studied art in many forms during my undergraduate education, including fashion design, art history, 2D and 3D art.  After studying abroad in Germany and learning the language I settled on a liberal arts degree that encompassed both my art and language studies.  <span class="highlight">In 2012 I graduated summa cum laude with a BA in Global Studies and a minor in German.</span>
	</p>
	<p>
		I strongly believe that the introduction of foreign language to my education was a game changer.  I still encourage all young people I meet to at least attempt a second language and to study abroad when the opportunity arises.  Learning a second language opened my mind and pushed me out of my comfort zone enough to teach me that it was a good thing!  My experiences abroad are always a reminder that I am capable of so much more than I or anyone else may think.  So far it's proved true!
	</p>
	<p>
		After graduating I opened myself to any opportunity that came my way.  Having been fairly broad in my education, I was not on a straight path, career-wise.  I worked in law, education, and even started a small, personal jewelry design business.  I learned a lot from each endeavor.  Turns out I'm not cut out to be a lawyer (this one didn't surprise me), I'm better with kids than I expected, and I'm pretty decent at making jewelry!  
	</p>
	<p>
		From these, and  many other lessons learned, I concluded that it was time to focus a bit and go back to school.  <span class="highlight">In August 2016 I began taking classes toward my MS in Applied Computer Science.</span>  I began the program with a solid career as my goal.  I figured I'd learn something new and stretch my comfort zone, once again.
	<h5>My Present</h5>
	<p>
		It was an interesting switch, that I was a little intimidated by at first, moving from the creative, right-brained mindset to the logical, analytical mindset necessary to pick up the basics of Object Oriented Programming.  Once I made the switch, it was refreshing to stretch my mind and learn something new and so functional, for lack of a better word.  
	</p>
	<p>
		One of my favorite things about creating jewelry, or any other art for that matter, is having the physical, finished product in your hand to wear.  Running my first Java program was that feeling times ten.  Every time I've finished a school project I call my fiance over and say, "Press this button!  Look what I made!"
	</p>
	<p>
		Early in my education I discovered web development and how much I enjoy the combination of creativity and logic.  I enjoyed front end design, but once I began learning back-end technologies my true love developed.  I learned the basics using a WAMP stack, but have since immersed myself in the fantastic framework that is Ruby on Rails.  Again, this type of development appeals to my creative side, my logical mindset, and also my love of being able to say, "Look at this!  I made it and you can use it!"
	</p>
	<p>
		In relation to web development, and really all development environments, I have also found a love of data and database technologies.  <span class="highlight">I am currently, as of April 2018, engaging in an internship as a Database Administrator.</span>  I have plenty of experience with SQL and limited experience with NoSQL and MongoDB.  I really enjoy the design of database schemas and 
	<h5>My Future</h5>
	<p>
		I will grate in July 2018 with my masters degree and look forward to moving (hopefully) smoothly By graduation I hope to have a full-time position as a Rails developer.  I am giddy with excitment about what the future will bring.  Life as already proven that you get back what you put in, and I'm putting everything I've got into this!  I truly look forward to what the future holds.
	</p>
	<p>
		On a more personal note, I am also getting married in October 2018.  I look forward to sharing that experience as part of my lifestyle blog <a href="#">here</a>!
	</p>
	<h4>A bit more about me...</h4>

	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h5>I love a good hike!</h5>
				<div class="thumbnail">
				  <%= image_tag "sweetwater_pano.jpg", :class => "figure-img img-fluid rounded" %>
				  <div class="caption">
				  	Georgia has some great hiking spots.  You can find this spectacular view in Sweetwater State Park!
				  </div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-4">
				<h5>I love to sew!</h5>
				<div class="thumbnail">
				  <%= image_tag "sewing.jpg", :class => "figure-img img-fluid rounded" %>
				  <div class="caption">
				  	I learned the basics of clothing construction while studying fashion design and have continued to improvise on my own.  I especially enjoy sewing vintage patterns or patterns of my own devise!
				  </div>
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
			<h5>I love escape rooms!</h5>
				<div class="thumbnail">
				  <%= image_tag "escape_room.jpg", :class => "figure-img img-fluid rounded" %>
				  <div class="caption">
				  	A friend invited us to an escape room in 2014 and we've been hooked ever since.  Fun fact: Ty actually proposed at our favorite escape room.
				  </div>
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
				<h5>I love hackathons!</h5>
				<div class="thumbnail">
				  <%= image_tag "hackathon.jpg", :class => "figure-img img-fluid rounded" %>
				  <div class="caption">
				  	This was my team at the #HackAgainstViolence hackathon in Atlanta--we won 3rd place!  I have since mentored a teen hackathon at UWG.  They are always intense but so much fun!
				  </div>
				</div>
			</div>
		</div>
	</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>